services:
  sftp:
    image: atmoz/sftp:latest
    ports:
      - "2222:22"
    volumes:
      - ./bais-emulator/data:/home
    command: >
      BTEckoh-report::1001
      CAPS-report::1002
      AllPay::1003
      NATWEST::1004