services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.35.0-arm64
    platform: linux/arm64
    restart: always
    command: >
      azurite --loose
      --blobHost 0.0.0.0 --blobPort 10000
      --location /data
      --skipApiVersionCheck
    ports:
      - "${AZURITE_PORT:-10000}:10000"
    volumes:
      - ./azurite-data:/data
    networks:
      - storage-emulator

networks:
  storage-emulator: