services:
  storage-account-roleMapping:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: roleMapping
    ports:
      - "${AZURITE_PORT:-10000}:10000"
    volumes:
      - ./storage-data/roleMapping:/data
    command: "azurite-blob --loose --blobHost 0.0.0.0 --skipApiVersionCheck"
    networks:
      storage-emulator:
        aliases: [ "storage-emulator"]
networks:
  storage-emulator:
