include:
  - path: ./docker-compose.yml
  - path: ./docker-compose-service-bus.yml

services:
  opal-maintenance-service:
    env_file:
      - ./docker-files/.env.shared
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
      - OPAL_MAINTENANCE_DB_HOST=opal-db
      - OPAL_MAINTENANCE_DB_PORT=5432
      - OPAL_MAINTENANCE_DB_NAME=opal-maintenance-db
      - OPAL_MAINTENANCE_DB_USERNAME=opal-db-user
      - OPAL_MAINTENANCE_DB_PASSWORD=opal-db-password
      - OPAL_REDIS_ENABLED=false
      - REDIS_CONNECTION_STRING=redis://redis:6379
      - TESTING_SUPPORT_ENDPOINTS_ENABLED=false
      - OPAL_USER_SERVICE_API_URL=http://host.docker.internal:4555/
      - SERVICEBUS_CONNECTION_STRING=Endpoint=sb://sb-emulator/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=local;UseDevelopmentEmulator=true
      - SERVICEBUS_LOGGING_PDPL_PROTOCOL=amqp
      - SERVICEBUS_LOGGING_PDPL_QUEUE_NAME=logging-pdpl
      - RUN_DB_MIGRATION_ON_STARTUP=true
    ports:
      - "${MAINTENANCE_PORT:-4551}:4551"
    depends_on:
      - opal-db
      - redis
      - azure-sb-emulator
    networks:
      - default
      - sb-emulator
    image: opal-maintenance-service:local
    build:
      context: ../opal-maintenance-service
      args:
        - http_proxy
        - https_proxy
        - no_proxy
